### ISSUE TITLE
Adding Sonatype OSS Index as new Strategy ?

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/vuln#19]
SonaType have a REST API to search for vulnerabilities. Not sure how exactly how it work and if this make sense to implement this in Vuln. But we can always try and see.

https://ossindex.sonatype.org/rest

**Comment by fraxken** [comment]
Contributions are welcome. Check [this guide](https://github.com/NodeSecure/vuln/blob/main/docs/adding_new_strategy.md) to learn how to add a new strategy.

**Comment by antoine-coulon** [comment]
Hello @fraxken, started here https://github.com/NodeSecure/vuln/pull/21
